---
- hosts: kubecluster
  become: yes
  roles:
    - common
    - docker
    - kube

- hosts: control
  become: yes
  roles:
    - kube-deploy
  
  environment:
    - KUBECONFIG: /etc/kubernetes/admin.conf

- hosts: armnodes
  become: yes
  roles:
    - node-join

- hosts: x86nodes
  become: yes
  roles:
    - node-join
