---
- name: Confirm an up-to-date apt cache is on the system
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: update core packages 
  apt:
    name: '*'
    state: latest
  notify: 
    - reboot server

# per docs at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#ensure-iptables-tooling-does-not-use-the-nftables-backend
- name: ensure iptables is using legacy mode binaries
  alternatives:
    name: '{{ item }}'
    path: /usr/sbin/{{ item }}-legacy
  with_items: '{{ iptables_legacy_bins }}'

# https://wiki.ubuntu.com/ARM/RaspberryPi#Raspberry_Pi_packages
- name: add memory cgroup config to boot params
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: '(fixrtc)$'
    replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1'
  when: inventory_hostname in groups['armnodes'] or inventory_hostname in groups['control']
  notify: 
    - reboot server

- name: Disable SWAP in fstab since kube can't work with swap
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  notify: 
    - reboot server

- name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reboot server

- name: deploy resolv.conf template
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: 
    - reboot server
